---
- name: group creation
  hosts: web
  tasks:
    - name: create a group dba
      group:
        name: dba
        state: present

    - name: create a user.
      user:
        name: john
        state: present
        groups: dba
